version: "3"

services:
  database :
      image: "postgres:13-alpine"
      environment:
          POSTGRES_USER: "cardMMO"
          POSTGRES_DB: "cardMMO"
          POSTGRES_PASSWORD: "cardmmo"
      volumes:
          - "cardMMO:/var/lib/postgresql/data"
      ports:
          - 5432:5432

volumes:
    cardMMO: